"""empty message

Revision ID: 458a7da0c9da
Revises: 
Create Date: 2018-05-01 21:15:27.029811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458a7da0c9da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rijeci',
    sa.Column('rijec', sa.Unicode(length=60), nullable=False),
    sa.Column('konkretnost_m', sa.Float(), nullable=True),
    sa.Column('konkretnost_std', sa.Float(), nullable=True),
    sa.Column('predocivost_m', sa.Float(), nullable=True),
    sa.Column('predocivost_std', sa.Float(), nullable=True),
    sa.Column('dob_usvajanja_m', sa.Float(), nullable=True),
    sa.Column('dob_usvajanja_std', sa.Float(), nullable=True),
    sa.Column('subj_frekvencija_m', sa.Float(), nullable=True),
    sa.Column('subj_frekvencija_std', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rijec')
    )
    op.create_index(op.f('ix_rijeci_dob_usvajanja_m'), 'rijeci', ['dob_usvajanja_m'], unique=False)
    op.create_index(op.f('ix_rijeci_dob_usvajanja_std'), 'rijeci', ['dob_usvajanja_std'], unique=False)
    op.create_index(op.f('ix_rijeci_konkretnost_m'), 'rijeci', ['konkretnost_m'], unique=False)
    op.create_index(op.f('ix_rijeci_konkretnost_std'), 'rijeci', ['konkretnost_std'], unique=False)
    op.create_index(op.f('ix_rijeci_predocivost_m'), 'rijeci', ['predocivost_m'], unique=False)
    op.create_index(op.f('ix_rijeci_predocivost_std'), 'rijeci', ['predocivost_std'], unique=False)
    op.create_index(op.f('ix_rijeci_subj_frekvencija_m'), 'rijeci', ['subj_frekvencija_m'], unique=False)
    op.create_index(op.f('ix_rijeci_subj_frekvencija_std'), 'rijeci', ['subj_frekvencija_std'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rijeci_subj_frekvencija_std'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_subj_frekvencija_m'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_predocivost_std'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_predocivost_m'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_konkretnost_std'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_konkretnost_m'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_dob_usvajanja_std'), table_name='rijeci')
    op.drop_index(op.f('ix_rijeci_dob_usvajanja_m'), table_name='rijeci')
    op.drop_table('rijeci')
    # ### end Alembic commands ###
